const usuarios = [
  {
    id: 1,
    nombre: "John",
    apellido: "Doe",
    edad: 25,
    sexo: "M",
    email: "john.doe@example.com",
  },
  {
    id: 2,
    nombre: "Jane",
    apellido: "Smith",
    edad: 30,
    sexo: "F",
    email: "jane.smith@example.com",
  },
  {
    id: 3,
    nombre: "Michael",
    apellido: "Johnson",
    edad: 35,
    sexo: "M",
    email: "michael.johnson@example.com",
  },
  {
    id: 4,
    nombre: "Emily",
    apellido: "Brown",
    edad: 28,
    sexo: "F",
    email: "emily.brown@example.com",
  },
  {
    id: 5,
    nombre: "David",
    apellido: "Miller",
    edad: 32,
    sexo: "M",
    email: "david.miller@example.com",
  },
  {
    id: 6,
    nombre: "Olivia",
    apellido: "Davis",
    edad: 27,
    sexo: "F",
    email: "olivia.davis@example.com",
  },
  {
    id: 7,
    nombre: "Daniel",
    apellido: "Wilson",
    edad: 29,
    sexo: "M",
    email: "daniel.wilson@example.com",
  },
  {
    id: 8,
    nombre: "Sophia",
    apellido: "Anderson",
    edad: 31,
    sexo: "F",
    email: "sophia.anderson@example.com",
  },
  {
    id: 9,
    nombre: "Matthew",
    apellido: "Taylor",
    edad: 26,
    sexo: "M",
    email: "matthew.taylor@example.com",
  },
  {
    id: 10,
    nombre: "Ava",
    apellido: "Thomas",
    edad: 33,
    sexo: "F",
    email: "ava.thomas@example.com",
  },
  {
    id: 11,
    nombre: "Andrew",
    apellido: "Harris",
    edad: 24,
    sexo: "M",
    email: "andrew.harris@example.com",
  },
  {
    id: 12,
    nombre: "Isabella",
    apellido: "Clark",
    edad: 36,
    sexo: "F",
    email: "isabella.clark@example.com",
  },
  {
    id: 13,
    nombre: "James",
    apellido: "Lewis",
    edad: 23,
    sexo: "M",
    email: "james.lewis@example.com",
  },
  {
    id: 14,
    nombre: "Mia",
    apellido: "Lee",
    edad: 34,
    sexo: "F",
    email: "mia.lee@example.com",
  },
  {
    id: 15,
    nombre: "Benjamin",
    apellido: "Walker",
    edad: 25,
    sexo: "M",
    email: "benjamin.walker@example.com",
  },
  {
    id: 16,
    nombre: "Charlotte",
    apellido: "Hall",
    edad: 30,
    sexo: "F",
    email: "charlotte.hall@example.com",
  },
  {
    id: 17,
    nombre: "William",
    apellido: "Young",
    edad: 27,
    sexo: "M",
    email: "william.young@example.com",
  },
  {
    id: 18,
    nombre: "Scarlett",
    apellido: "King",
    edad: 29,
    sexo: "F",
    email: "scarlett.king@example.com",
  },
  {
    id: 19,
    nombre: "Joseph",
    apellido: "Baker",
    edad: 32,
    sexo: "M",
    email: "joseph.baker@example.com",
  },
  {
    id: 20,
    nombre: "Grace",
    apellido: "Gonzalez",
    edad: 28,
    sexo: "F",
    email: "grace.gonzalez@example.com",
  },
];

module.exports = usuarios;
